version: '3'
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: bot_discord
    ports:
      - '5432:5432'

  simple_bot:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bot_discord
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty
    links:
      - "db:db"
    ports:
      - "8080:8080"
    depends_on:
      - db
